cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    s3:
      bucketName: handtris
      defaultImage: https://handtris.s3.ap-northeast-2.amazonaws.com/profile/defaultImage.png