spring:
  application:
    name: HandTris
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  datasource:
    url: ENC(C563BBvp/byHXUyveKzrDBTmZ02YJYBXitwSeSahSWLp5LhFPLW+huwejuscAcheICOXkpOGusa8za+7GJyuNOmOP2txDUA+eEyWWlfRipUB9jzksnwvwzhSLWKJ2mNk)
    username: ENC(52ifzpYF4pXoaZ/Sf3d5iKQ6CTqZEJNT)
    password: ENC(Sjwbg9dA1ZW5l7IWOYHt2ovH3zyhvmtsXAlMzYNpWAJEj4ntVhV4Zg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
jasypt:
  encryptor:
    bean: jasyptStringEncryptor