spring:
  application:
    name: HandTris
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
        format_sql: true
        show_sql: true
  datasource:
    url: ENC(RUIwyNsThoZ0LzHXNQB+3hHU7otlV461EYNpbFPK3chWGZUM8OXShCqdjg/0HI+ndc6eHD9uV/to2RM8nGlOWytJXYUx+fqsQGKuG/cqWzrq1V0eKjn9lg==)
    username: ENC(N3QGcbod6LQ3O6PqNCx1ffBt+xRc72OW)
    password: ENC(8era+ZliemtYHHjJnhuz0tqmYeTFYRafSdUoCsFQT5XKJkImCA8oSg==)
    driver-class-name: com.mysql.cj.jdbc.Driver