spring:
  application:
    name: HandTris
  profiles:
    # todo : commit 시 prod로 변경
    active:
      - dev
    group:
      dev:
        - dev
      prod:
        - prod

jasypt:
  encryptor:
    bean: jasyptStringEncryptor