spring:
  application:
    name: HandTris
  profiles:
    active:
      - prodd
    group:
      dev:
        - dev
        - jwt
      prod:
        - prod
        - jwt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor